# Задание 1

In [42]:
import numpy as np

In [43]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a_t = np.transpose(a)
print(a_t)
type(a_t)
#b = np.array(a_t, dtype = float)
a_t.shape

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


(5, 2)

In [44]:
a_t.mean(axis=0)
a_t_mean = a.mean(axis=0)
print(a_mean)
#print("Средние значения по признаку: {}".format(a.mean(axis=1)))
print("Форма a {}".format(a_t.shape))

[2.  8.4]
Форма a (5, 2)


# Задание 2

In [45]:
a_centered = a_t - a_mean
#a_centered = np.subtract(a_t, a_mean)
#a_centered = a[:, np.newaxis] - a_mean
print(a_centered)
a_centered.shape

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


(5, 2)

### Задание 3

In [54]:
At = np.transpose(a_centered)
At
a_centered_sp = np.dot(a_centered, At)
a_centered_sp
# a_centered @ a_centered
#I = np.eye(2)
#I
#a_centered_sp = np.dot(a_centered, I)
#a_centered_sp

array([[ 6.76,  0.96, -7.24, -4.84,  4.36],
       [ 0.96,  0.16, -1.04, -0.64,  0.56],
       [-7.24, -1.04,  7.76,  5.16, -4.64],
       [-4.84, -0.64,  5.16,  3.56, -3.24],
       [ 4.36,  0.56, -4.64, -3.24,  2.96]])

In [70]:
dev_centered = a_centered_sp / 4
dev_centered

array([[ 1.69,  0.24, -1.81, -1.21,  1.09],
       [ 0.24,  0.04, -0.26, -0.16,  0.14],
       [-1.81, -0.26,  1.94,  1.29, -1.16],
       [-1.21, -0.16,  1.29,  0.89, -0.81],
       [ 1.09,  0.14, -1.16, -0.81,  0.74]])

In [74]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a_ds = np.dstack(a)
print(a_ds)
type(a_ds)
#b = np.array(a_t, dtype = float)
a_ds.shape

[[[ 1  6]
  [ 2  8]
  [ 3 11]
  [ 3 10]
  [ 1  7]]]


(1, 5, 2)